### ISSUE TITLE
[BUG] Unable to change status of incident

### ISSUE THREAD

**Issue by initharrington** [incidentbot/incidentbot#596]
**Describe the bug**

Unable to change the status of an incident.  I am not sure if it is my configuration or issue with v2.

**Version**
2.0.4

**To Reproduce**

In an active incident I do,

`/incidentbot this`

I click set status
Change to "identified" or "monitoring"

Nothing happens and I get this error in pod logs:

```
Error: IncidentChannelDigestNotification.update() got an unexpected keyword argument 'postmortem_link'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/usr/local/lib/python3.12/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
           ^^^^^^^^^^^^^^^^^^
  File "/app/incidentbot/slack/command.py", line 425, in handle_submission
    asyncio.run(
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/incidentbot/incident/actions.py", line 741, in set_status
    blocks=IncidentChannelDigestNotification.update(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: IncidentChannelDigestNotification.update() got an unexpected keyword argument 'postmortem_link'
```

**Expected behavior**
I expect the status to change

**Screenshots**
![image](https://github.com/user-attachments/assets/0ab579e6-d406-4c0d-ad7c-53adf25f7842)

**Environment (please complete the following information):**
k8s/helm 

**Additional context**
I have the defaults setup in helm besides digest_channel.  Haven't setup anything for post mortem.

```
configMap:
  create: true
  data:
    digest_channel: diffname
```

**Comment by echoboomer** [comment]
@initharrington just released `v2.0.5` - let me know if this solves your issue.

**Comment by initharrington** [comment]
@echoboomer not getting that error anymore. thanks!

**Comment by pfallasro** [comment]
@echoboomer I'm running into this issue but I can't see the fix on [dockerhub](https://hub.docker.com/r/eb129/incident-bot/tags)

Can you make it available?
