### ISSUE TITLE
[BUG] get_slack_user "real_name" returned None

### ISSUE THREAD

**Issue by initharrington** [incidentbot/incidentbot#597]
**Describe the bug**
This is an edge case issue.  I was working on deploying the app and hit a slack rate limit.

```
2024-09-24 14:25:37 [error    ] Error getting user list from Slack workspace: The request to the Slack API failed. (url: https://slack.com/api/users.list)
The server responded with: {'ok': False, 'error': 'ratelimited'}
2024-09-24 14:25:37 [info     ] Found 0 Slack users
```

I then went to my test incident and tried to update my role (didn't matter which one).
I then got this error in the pod logs:

```
Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/usr/local/lib/python3.12/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
           ^^^^^^^^^^^^^^^^^^
  File "/app/incidentbot/slack/handler.py", line 407, in handle_join_this_incident
    asyncio.run(
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/incidentbot/incident/actions.py", line 226, in join_incident_as_role
    EventLogHandler.create(
  File "/app/incidentbot/incident/event.py", line 32, in create
    (get_slack_user(user)["real_name"] if user != "" else None)
     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
```

https://github.com/incidentbot/incidentbot/blob/main/incidentbot/incident/event.py#L32

**Version**
v2.0.4

**To Reproduce**
1. Hit slack rate limit
2. zero users imported
3. try to claim a role in an incident

**Expected behavior**
It fixed itself after no longer hitting the rate limit.

**Screenshots**
NA

**Environment (please complete the following information):**
k8s/helm

**Additional context**
NA

**Comment by echoboomer** [comment]
@initharrington just released `v2.0.5` - this should take care of this and similar issues with retry logic for Slack API calls. Thanks for reporting this.
